### ISSUE TITLE
Test csw:csw-2.0.2-GetCapabilities-tc1.1 fails if capabilities contains ExtendedCapabilities

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-csw202#23]
## Setup
SUT: TODO
Tested with [production ](http://cite.opengeospatial.org/teamengine/)
 * ETS CSW 1.16 
 * TEAM Engine 4.10

and local docker environment
 * ETS CSW 1.18-SNAPSHOT
 * TEAM Engine 5.2

## Testfailure
The three subtests fails:
 * ctl:XMLValidatingParser.HINTS
   * Error 1: cvc-elt.1.a: Cannot find the declaration of element 'csw:Capabilities'.
 * ctl:XMLValidatingParser.CSW
   *  Error: Null input document.
 * ctl:SchematronValidatingParser
   * Error: Null input document.

In the teamengine log the following stacktrace is logged:
```
Mar 22, 2018 3:47:36 PM com.occamlab.te.TECore findXMLResource
WARNING: Failed to parse classpath resource /csw-prune.xsl
java.lang.NullPointerException
	at com.occamlab.te.TECore.findXMLResource(TECore.java:2577)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by lgoltz** [comment]
Fixed with #30
